config/routes.rb
Rails.application.routes.draw do
  resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end 

  def create
    @post = Post.new(post_params)

    if @post.save
        redirect_to @post
    else 
        render 'new'
    end 
  end

  def show 
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update 
    @post = Post.find(params[:id])

    if @post.update(post_params)
    redirect_to @post
    else 
    render 'edit'
    end  
  end

  def destroy 
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to @post
  end
  private 

  def post_params
  params.require(:post).permit(:title, :body)
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= link_to "Home", posts_path %>
<%= link_to "New Post", new_post_path %>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<h1>Edit Post</h1> 

<%= form_for @post do |f| %>
  <%= f.label :Title %>:
  <%= f.text_field :title %><br>
  <br>
  <%= f.label :tessst %>:
  <%= f.text_area :body %><br>
  <br>
  <%= f.submit %>
<% end %>

app/views/posts/index.html.erb
<h1>All the posts are here</h1>
<% for x in @posts %>
<p>the title of the post is: <%= x.title %></p>
<p>the body of the post is: <%= x.body %></p>
<%= link_to "Read Post", x %>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_for @post do |f| %>
  <%= f.label :Title %>:
  <%= f.text_field :title %><br>
  <br>
  <%= f.label :tessst %>:
  <%= f.text_area :body %><br>
  <br>
  <%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<div><%= @post.body %><div>

<%= link_to "Edit Post", edit_post_path(@post)%>
<%= link_to "Delete Post", post_path(@post), method: :delete, data: { confirm: "are you sure bro?" } %>